function outTable = import_and_parse_jatos_individual_file(filename)
%IMPORTFILE Import data from a text file
%  STUDY00426RESULTID32284WORKERID15653AUTOEXPORT = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  STUDY00426RESULTID32284WORKERID15653AUTOEXPORT = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Study00426ResultID32284WorkerID15653AUTOEXPORT = importfile("C:\Users\levan\GitHub\concept_gen_analysis\data\jatos_individual_exports\batch_3_wave_10\Study00426_ResultID-32284_WorkerID-15653_AUTO_EXPORT.jatos", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Feb-2021 15:06:36

%% Input handling
dataLines = [2, Inf];

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ComponentResultID", "ComponentID", "ComponentResultTime", "StudyResultID", "WorkerID", "Data"];
opts.VariableTypes = ["double", "double", "datetime", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Data", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Data", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ComponentResultTime", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
outTable = readtable(filename, opts);

end