---
title: "Analyzing Mouse Euclidean Distance data"
output:
  html_document:
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Setup: load data, define variables, etc

```{r load-data-define-variables}

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

# Load an external script which contains functions for estimating either just the learning rate, or also the asymptote
source('./scripts/utils/functions_for_fitting_learning_curves.R')

# Create parameters as starting points for estimations
i_start <- 0.5
c_start <- 0.1

# Create lower and upper bound constraints on the asymptote and learning rate
c_lower <- 0
c_upper <- Inf
i_lower <- 0
i_upper <- Inf

qc_filter <- F

```

# Do all the calculations of all the dependent variables

```{r analyze-dependent-variables}

exclude_border <- F

border_dist_to_exclude <- c()

source('./scripts/analysis/analyze_dependent_variables.R')


```

```{r order-of-conditions}

# For each participant, list the order of conditions
condition_orders <- tibble(.rows = 5)

all_ptp <- unique(session_results_all_ptp$ptp)

for (iPtp in as.vector(all_ptp)){
        iPtp
        condition_orders[iPtp] <-
                unique(
                        session_results_all_ptp$condition[
                                session_results_all_ptp$ptp==iPtp
                                ])
}

```

# Learning curve plots

## Raw learning curves + learning fits

```{r raw-learning-curves-and-fits, fig.width=13, fig.height=12}

# Plot the fits
fig_each_ptp <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('correct_exact'),
               new_pa_status == 'both') %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean)) +
        geom_point() +
        geom_line() +

        # Add the y_hat learning and intercept
        geom_line(aes(x=new_pa_img_row_number_across_sessions,
                      y=y_hat_i_c),
                  size=1,
                  color='blue',
                  linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('Exact correct: real and estimate data',sep='')) +
        xlab('Image repetition') +
        ylab('Correct Exact') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') +
        geom_text(data=filter(
                learning_and_intercept_each_participant,
                accuracy_type %in% c('correct_exact'),
                new_pa_status == 'both'
                ),
                aes(x=4,
                    y=0.65,
                    label = paste('conv=',
                                  as.character(convergence),
                                  ' ',
                                  'i=',
                                  as.character(round(i,2)),
                                  ' ',
                                  'c=',
                                  as.character(round(c,2)),
                                  seq='')))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp)

# Now, plot with one square away

# Plot the fits
fig_each_ptp <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('correct_one_square_away'),
               new_pa_status == 'both') %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean)) +
        geom_point() +
        geom_line() +

        # Add the y_hat learning and intercept
        geom_line(aes(x=new_pa_img_row_number_across_sessions,
                      y=y_hat_i_c),
                  size=1,
                  color='red',
                  linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('One square away: real and estimate data',sep='')) +
        xlab('Image repetition') +
        ylab('Correct One Square Away') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') +
        geom_text(data=filter(
                learning_and_intercept_each_participant,
                accuracy_type %in% c('correct_one_square_away'),
                new_pa_status == 'both'
                ),
                aes(x=5.5,
                    y=0.15,
                    label = paste('conv=',
                                  as.character(convergence),
                                  ' ',
                                  'i=',
                                  as.character(round(i,2)),
                                  ' ',
                                  'c=',
                                  as.character(round(c,2)),
                                  seq='')))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp)

# Now, plot with euclidean distance

# Plot the fits
fig_each_ptp <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('mouse_error'),
               new_pa_status == 'both') %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean)) +
        geom_point() +
        geom_line() +

        # Add the y_hat learning and intercept
        geom_line(aes(x=new_pa_img_row_number_across_sessions,
                      y=y_hat_i_c),
                  size=1,
                  color='orange',
                  linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('Mouse euclidean distance',sep='')) +
        xlab('Image repetition') +
        ylab('Mouse euclidean distance ') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') +
        geom_text(data=filter(
                learning_and_intercept_each_participant,
                accuracy_type %in% c('mouse_error'),
                new_pa_status == 'both'
                ),
                aes(x=4.5,
                    y=200.15,
                    label = paste('conv=',
                                  as.character(convergence),
                                  ' ',
                                  'i=',
                                  as.character(round(i,2)),
                                  ' ',
                                  'c=',
                                  as.character(round(c,2)),
                                  seq='')))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp)

```

```{r learning-curves-across-part, fig.width=13, fig.height=4}

# Plot the fits
fig_each_ptp <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('mouse_error'),
               new_pa_status == 'both') %>%
        droplevels() %>%                
        group_by(condition,
                 new_pa_img_row_number_across_sessions) %>%
        summarise(n = n(),
                  correct_mean_across_ptp = mean(correct_mean,na.rm = T)) %>% 
        ungroup() %>%
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean_across_ptp)) +
        geom_point() +
        geom_line() +

        facet_grid(~condition) +
        ggtitle(paste('Mouse euclidean distance; Across participants',sep='')) +
        xlab('Image repetition') +
        ylab('Mouse euclidean distance ') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') 


print(fig_each_ptp)


```

```{r learning-curves-across-part-ech-border-dist, fig.width=13, fig.height=4}

# Plot the fits
fig_each_ptp <- sum_stats_by_border_distance %>%
        filter(accuracy_type %in% c('mouse_error')) %>%
        droplevels() %>%       
        group_by(condition,
                 border_dist,
                 new_pa_img_row_number_across_sessions) %>%
        summarise(n = n(),
                  correct_mean_across_ptp = mean(correct_mean,na.rm = T)) %>% 
        ungroup() %>%
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean_across_ptp,
                   group=border_dist,
                   color=border_dist)) +
        geom_point() +
        geom_line() +

        facet_grid(~condition) +
        ggtitle(paste('Mouse euclidean distance; Across participants; By border distance',sep='')) +
        xlab('Image repetition') +
        ylab('Mouse euclidean distance ') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') 


print(fig_each_ptp)

# Plot the fits
fig_each_ptp <- sum_stats_by_border_distance %>%
        filter(accuracy_type %in% c('correct_exact','correct_one_square_away')) %>%
        droplevels() %>%       
        group_by(condition,
                 border_dist,
                 new_pa_img_row_number_across_sessions,
                 accuracy_type) %>%
        summarise(n = n(),
                  correct_mean_across_ptp = mean(correct_mean,na.rm = T)) %>% 
        ungroup() %>%
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean_across_ptp,
                   group=border_dist,
                   color=border_dist)) +
        geom_point() +
        geom_line() +

        facet_grid(accuracy_type~condition) +
        ggtitle(paste('Accuracy data; Across participants; By border distance',sep='')) +
        xlab('Image repetition') +
        ylab('Accuracy ') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') 


print(fig_each_ptp)


```


## Learning curves: Landmark vs non-landmark

```{r landmark-raw-learning-curves-and-fits, fig.width=10, fig.height=12}

# Plot the fits
fig_each_ptp_lm <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('correct_exact'),
               new_pa_status %in% c('near_pa','far_pa'),
               !condition %in% c('random_locations','no_schema')) %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean,
                   group=new_pa_status,
                   color=new_pa_status)) +
        geom_point() +
        geom_line(size=1) +
# 
        # Add the y_hat learning and intercept
        geom_line(aes(x=new_pa_img_row_number_across_sessions,
                      y=y_hat_i_c),
                  size=1,
                  # color='blue',
                  linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('Exact correct: real and estimate data',sep='')) +
        xlab('Image repetition') +
        ylab('Correct Exact') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') +
        geom_text(data=filter(
                learning_and_intercept_each_participant,
                accuracy_type %in% c('correct_exact'),
                new_pa_status %in% c('near_pa','far_pa'),
                !condition %in% c('random_locations','no_schema')
                ),
                aes(x=3.5,
                    y=0.65,
                    label = paste('conv=',
                                  as.character(convergence),
                                  ' ',
                                  'i=',
                                  as.character(round(i,2)),
                                  ' ',
                                  'c=',
                                  as.character(round(c,2)),
                                  seq='')),
                position=ggstance::position_dodgev(height=0.3))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp_lm)

# Plot the fits
fig_each_ptp_lm <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('correct_one_square_away'),
               new_pa_status %in% c('near_pa','far_pa'),
               !condition %in% c('random_locations','no_schema')) %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean,
                   group=new_pa_status,
                   color=new_pa_status)) +
        geom_point() +
        geom_line(size=1) +
# 
        # Add the y_hat learning and intercept
        geom_line(aes(x=new_pa_img_row_number_across_sessions,
                      y=y_hat_i_c),
                  size=1,
                  # color='blue',
                  linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('correct_one_square_away: real and estimate data',sep='')) +
        xlab('Image repetition') +
        ylab('correct_one_square_away') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') +
        geom_text(data=filter(
                learning_and_intercept_each_participant,
                accuracy_type %in% c('correct_one_square_away'),
                new_pa_status %in% c('near_pa','far_pa'),
                !condition %in% c('random_locations','no_schema')
                ),
                aes(x=3.5,
                    y=0.65,
                    label = paste('conv=',
                                  as.character(convergence),
                                  ' ',
                                  'i=',
                                  as.character(round(i,2)),
                                  ' ',
                                  'c=',
                                  as.character(round(c,2)),
                                  seq='')),
                position=ggstance::position_dodgev(height=0.3))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp_lm)

# For mouse euclidean distance

fig_each_ptp_lm <- mean_by_rep_all_types_long %>%
        filter(accuracy_type %in% c('mouse_error'),
               new_pa_status %in% c('near_pa','far_pa'),
               !condition %in% c('random_locations','no_schema')) %>%
        droplevels() %>%        
        ggplot(aes(x=new_pa_img_row_number_across_sessions,
                   y=correct_mean,
                   group=new_pa_status,
                   color=new_pa_status)) +
        geom_point() +
        geom_line(size=1) +
# 
        # Add the y_hat learning and intercept
        # geom_line(aes(x=new_pa_img_row_number_across_sessions,
        #               y=y_hat_i_c),
        #           size=1,
        #           # color='blue',
        #           linetype = 'longdash') +

        facet_grid(ptp_trunk~condition) +
        ggtitle(paste('Mouse euclidean distance',sep='')) +
        xlab('Image repetition') +
        ylab('Mouse euclidean distance') +
        scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8)) +
        # theme(legend.position = 'top') +
        geom_vline(xintercept = 4.5, linetype = 'dashed') 
        # geom_text(data=filter(
        #         learning_and_intercept_each_participant,
        #         accuracy_type %in% c('correct_one_square_away'),
        #         new_pa_status %in% c('near_pa','far_pa'),
        #         !condition %in% c('random_locations','no_schema')
        #         ),
        #         aes(x=3.5,
        #             y=0.65,
        #             label = paste('conv=',
        #                           as.character(convergence),
        #                           ' ',
        #                           'i=',
        #                           as.character(round(i,2)),
        #                           ' ',
        #                           'c=',
        #                           as.character(round(c,2)),
        #                           seq='')),
        #         position=ggstance::position_dodgev(height=0.3))
        # geom_text(data=learning_only_each_participant,
        #           aes(x=7,y=0.05, label = paste('c=',as.character(round(c,2)),seq='')))        
        # annotate('text',x=1.5,y = 0.85, label = learning_and_asymptote_each_participant$a ,size=3)


print(fig_each_ptp_lm)


```


# Scatter plots of dependent variables:

## Rough measures: last 2 reps and last 4 reps

```{r plot-rough-measures-overall, fig.width=5, fig.height=4}

sum_stats_each_participant %>%
        filter(new_pa_status == 'both',
               accuracy_type == 'mouse_error') %>%
        droplevels() %>%
        ggplot(aes(x=condition,
                   y=last_four_mean)) +
        geom_violin() +
        geom_dotplot(binaxis = 'y',
                     stackdir = 'center',
                     stackratio = 1,
                     dotsize = 1,
                     fill = 'black',
                     alpha = 0.2) +
        geom_line(aes(group=ptp_trunk,
                      color=ptp_trunk)) +
        facet_wrap(~accuracy_type, nrow = 1) +
        stat_summary(fun=mean, geom="point", shape=20, size=5, 
                     color="red", fill="red") + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",size=1,width=0.1,color='red') +
        theme(legend.position = '') +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        ggtitle('Overall, last 4 reps')

sum_stats_each_participant %>%
        filter(new_pa_status == 'both',
               accuracy_type == 'mouse_error') %>%
        droplevels() %>%
        ggplot(aes(x=condition,
                   y=log_last_four_mean)) +
        geom_violin() +
        geom_dotplot(binaxis = 'y',
                     stackdir = 'center',
                     stackratio = 1,
                     dotsize = 1,
                     fill = 'black',
                     alpha = 0.2) +
        geom_line(aes(group=ptp_trunk,
                      color=ptp_trunk)) +
        facet_wrap(~accuracy_type, nrow = 1) +
        stat_summary(fun=mean, geom="point", shape=20, size=5, 
                     color="red", fill="red") + 
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",size=1,width=0.1,color='red') +
        theme(legend.position = '') +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        ggtitle('Overall, LOG last 4 reps')


```

### near_pa vs far_pa:

```{r plot-rough-measures-new_pa_status}

# Last 4
sum_stats_each_participant %>%
        filter(new_pa_status != 'both',
               !condition %in% c('random_locations','no_schema'),
               accuracy_type == 'mouse_error') %>%
        droplevels() %>%
        pivot_wider(id_cols = c(ptp_trunk,
                                condition,
                                accuracy_type),
                    names_from = new_pa_status,
                    values_from = last_four_mean) %>% 
        mutate(neighbor_diff = far_pa - near_pa) %>%
        ggplot(aes(x=condition,y=neighbor_diff)) +
        geom_violin() +
        # geom_jitter(width = 0.1, alpha = 0.2) +
        geom_dotplot(binaxis='y', stackdir='center',
                     stackratio=1, dotsize=1, fill="black",
                     alpha=0.3) +        
        geom_line(aes(group=ptp_trunk,
                      color=ptp_trunk)) +
        stat_summary(fun=mean, geom="point", shape=20, size=5, 
                     color="red", fill="red") +   
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",size=1,width=0.1,color='red') +        
        facet_wrap(~accuracy_type, nrow = 1) +
        ylab('Diff') + 
        theme(legend.position = '') +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        ggtitle('Far minus near-PA, last 4') +
        geom_hline(yintercept = 0, linetype = 'dashed')

```



## Learning rates:

### near_pa vs far_pa:

```{r scatter-plots-learning-rates-landmark, fig.width=8, fig.height=6}

sum_stats_each_participant %>%
        filter(new_pa_status != 'both',
               accuracy_type %in% c('mouse_error'),
               !condition %in% c('random_locations','no_schema')) %>%
        droplevels() %>%
        ggplot(aes(x=new_pa_status,
                   y=c_ml,
                   fill=new_pa_status)) +
        geom_violin(alpha=0.5) +
        geom_boxplot(width=0.2,
                     alpha=0.2) +
        geom_point(alpha=0.2) +
        geom_line(aes(group=ptp_trunk),
                  alpha=0.2) +
        stat_summary(fun=mean, 
                     geom="point", 
                     shape=20, 
                     size=5, 
                     color="black",
                     fill="black") +         
        facet_grid(accuracy_type~condition) +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        ylab('Learning Rate C')


# Log C
# sum_stats_each_participant %>%
#         filter(new_pa_status != 'both',
#                accuracy_type %in% c('mouse_error'),
#                !condition %in% c('random_locations','no_schema')) %>%
#         droplevels() %>%
#         ggplot(aes(x=new_pa_status,
#                    y=c_ml_log,
#                    fill=new_pa_status)) +
#         geom_violin(alpha=0.5) +
#         geom_boxplot(width=0.2,
#                      alpha=0.2) +
#         geom_point(alpha=0.2) +
#         geom_line(aes(group=ptp_trunk),
#                   alpha=0.2) +
#         stat_summary(fun=mean, 
#                      geom="point", 
#                      shape=20, 
#                      size=5, 
#                      color="black",
#                      fill="black") +         
#         facet_grid(~accuracy_type+condition) +
#         theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#         ylab('Log C') +
#         ggtitle('Log C')

```

Plot the difference values:

```{r learning-rates-difference-far_pa-near_pa, fig.width=5, fig.height=4}

# Learning rates
sum_stats_each_participant %>%
        filter(new_pa_status != 'both',
               !condition %in% c('random_locations','no_schema'),
               accuracy_type %in% c('mouse_error')) %>%
        droplevels() %>%
        pivot_wider(id_cols = c(ptp_trunk,
                                condition,
                                accuracy_type),
                    names_from = new_pa_status,
                    values_from = c) %>% 
        mutate(far_pa_diff = far_pa - near_pa) %>% 
        ggplot(aes(x=condition,y=far_pa_diff)) +
        geom_violin() +
        # geom_jitter(width = 0.1, alpha = 0.2) +
        # geom_dotplot(binaxis='y', stackdir='center',
        #              stackratio=1, dotsize=0.3, fill="black",
        #              alpha=0.3) +       
        geom_point(alpha=0.3) +
        geom_line(aes(group=ptp_trunk,
                      color=ptp_trunk)) +
        stat_summary(fun=mean, geom="point", shape=20, size=5,
                     color="purple", fill="purple") +
        stat_summary(fun.data = mean_cl_normal,
                     geom = "errorbar",size=1,width=0.1,color='purple') +
        facet_wrap(~accuracy_type, nrow = 1) +
        ylab('Diff') + 
        theme(legend.position = '') +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        ggtitle('Far minus near-PA, learning rate') +
        geom_hline(yintercept = 0, linetype = 'dashed')


```
